import argparse
import ast
import json
import re
from datetime import datetime
from pathlib import Path

from scripts.common.display_path import display_path
from scripts.common.path_normalization import normalize_repo_relative_path
from scripts.extract.server_blocks import _find_decorator_matches, _get_function_block
from scripts.extract.server_parameters import extract_parameters
from scripts.extract.server_returns import infer_returns

REPO_ROOT = Path(__file__).resolve().parents[2]

OUTPUT_PATH = REPO_ROOT / "references" / "raw" / "server_endpoints.json"
DOCSTRING_RE = re.compile(r'\s*[rubfRUBF]*(["\']{3})(.*?)\1', re.DOTALL)

ENDPOINT_COVERAGE = {
    "description": "Static extraction of ComfyUI HTTP and WebSocket endpoint structure.",
    "guaranteed_fields": [
        "endpoints[].route",
        "endpoints[].method",
        "endpoints[].returns.kind",
        "endpoints[].returns.status_codes",
    ],
    "best_effort_fields": [
        "endpoints[].description",
        "endpoints[].parameters",
        "endpoints[].returns.summary",
        "endpoints[].returns.fields",
        "endpoints[].returns.traceability",
        "prompt_submission_contract.request_fields",
        "prompt_submission_contract.success_response_fields",
        "prompt_submission_contract.error_response_fields",
        "prompt_validation_errors.error_types",
        "queue_history_contract.sections",
    ],
    "deferred": [
        "deep parameter typing and validation semantics",
        "full response-body fidelity for variable-return branches",
        "runtime node-specific validation generated by custom node VALIDATE_INPUTS implementations",
        "exact runtime history_result output payloads produced by node execution",
    ],
}

PROMPT_REQUEST_FIELD_DESCRIPTIONS = {
    "number": "Optional queue priority number; otherwise the server increments its internal counter.",
    "front": "Optional flag that negates the generated queue number when number is omitted.",
    "prompt": "Prompt graph payload passed to execution.validate_prompt.",
    "prompt_id": "Optional prompt identifier; defaults to a generated UUID.",
    "partial_execution_targets": "Optional list limiting which output nodes validate and execute.",
    "extra_data": "Optional metadata stored with the queued prompt.",
    "client_id": "Optional client identifier copied into extra_data.",
}

PROMPT_ERROR_SUMMARIES = {
    "no_prompt": "POST /prompt request did not include a prompt field.",
    "missing_node_type": "A prompt node is missing class_type or references an unknown node class.",
    "prompt_no_outputs": "The prompt contains no selected output nodes.",
    "prompt_outputs_failed_validation": "All candidate output nodes failed validation.",
    "exception_during_validation": "Validation raised while validating an output node.",
    "dependency_cycle": "Recursive validation detected a node dependency cycle.",
    "required_input_missing": "A required node input is absent from the prompt.",
    "bad_linked_input": "A linked input is not a length-two [node_id, slot_index] list.",
    "return_type_mismatch": "A linked node output type is incompatible with the target input type.",
    "exception_during_inner_validation": "Recursive validation of a linked inner node raised.",
    "invalid_input_type": "A widget value could not be converted to the expected input type.",
    "value_smaller_than_min": "A numeric value is smaller than the configured minimum.",
    "value_bigger_than_max": "A numeric value is larger than the configured maximum.",
    "value_not_in_list": "A value is not present in the configured option list.",
    "custom_validation_failed": "A node custom validation hook returned a failure.",
}


class _ParentAnnotator(ast.NodeVisitor):
    def visit(self, node):  # type: ignore[no-untyped-def]
        for child in ast.iter_child_nodes(node):
            setattr(child, "_parent", node)
        super().visit(node)


def _parse_python(source_text: str) -> ast.AST | None:
    if not source_text.strip():
        return None
    try:
        tree = ast.parse(source_text)
    except SyntaxError:
        return None
    _ParentAnnotator().visit(tree)
    return tree


def _function_nodes(tree: ast.AST | None) -> dict[str, ast.AST]:
    if tree is None:
        return {}
    return {
        node.name: node
        for node in ast.walk(tree)
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef)
    }


def _traceability(source_file: str | None, source_function: str, strategy: str) -> dict:
    return {
        "source_type": "pinned_snapshot",
        "strategy": strategy,
        "source_file": source_file,
        "source_function": source_function,
    }


def _field(
    name: str,
    location: str,
    required: bool,
    type_hint: str,
    description: str,
    traceability: dict,
) -> dict:
    return {
        "name": name,
        "location": location,
        "required": required,
        "type_hint": type_hint,
        "description": description,
        "traceability": traceability,
    }


def _deferred_section(reason: str, **lists: list) -> dict:
    return {
        **lists,
        "coverage": "deferred",
        "deferred_reason": reason,
    }


def _extract_string_keys_from_json_data(function_node: ast.AST) -> set[str]:
    keys: set[str] = set()
    for node in ast.walk(function_node):
        if isinstance(node, ast.Compare):
            left = node.left
            if (
                isinstance(left, ast.Constant)
                and isinstance(left.value, str)
                and any(isinstance(op, ast.In) for op in node.ops)
                and any(
                    isinstance(comp, ast.Name) and comp.id == "json_data"
                    for comp in node.comparators
                )
            ):
                keys.add(left.value)
        elif isinstance(node, ast.Subscript):
            if isinstance(node.value, ast.Name) and node.value.id == "json_data":
                slice_value = node.slice
                if isinstance(slice_value, ast.Constant) and isinstance(slice_value.value, str):
                    keys.add(slice_value.value)
        elif isinstance(node, ast.Call):
            if (
                isinstance(node.func, ast.Attribute)
                and node.func.attr == "get"
                and isinstance(node.func.value, ast.Name)
                and node.func.value.id == "json_data"
                and node.args
                and isinstance(node.args[0], ast.Constant)
                and isinstance(node.args[0].value, str)
            ):
                keys.add(node.args[0].value)
    return keys


def _literal_dict_keys(node: ast.AST) -> list[str]:
    if not isinstance(node, ast.Dict):
        return []
    keys = []
    for key in node.keys:
        if isinstance(key, ast.Constant) and isinstance(key.value, str):
            keys.append(key.value)
    return keys


def _json_response_payload_fields(function_node: ast.AST) -> tuple[set[str], set[str]]:
    success_fields: set[str] = set()
    error_fields: set[str] = set()
    assigned_dicts: dict[str, list[str]] = {}

    for node in ast.walk(function_node):
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Dict):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    assigned_dicts[target.id] = _literal_dict_keys(node.value)

    for node in ast.walk(function_node):
        if not (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr == "json_response"
            and node.args
        ):
            continue
        payload = node.args[0]
        keys = _literal_dict_keys(payload)
        if isinstance(payload, ast.Name):
            keys = assigned_dicts.get(payload.id, [])
        status: int | str | None = None
        for keyword in node.keywords:
            if keyword.arg == "status" and isinstance(keyword.value, ast.Constant):
                if isinstance(keyword.value.value, int | str):
                    status = keyword.value.value
        if status and int(status) >= 400:
            error_fields.update(keys)
        else:
            success_fields.update(keys)
    return success_fields, error_fields


def _extract_prompt_submission_contract(
    server_text: str,
    *,
    server_source: str | None = None,
) -> dict:
    functions = _function_nodes(_parse_python(server_text))
    post_prompt = functions.get("post_prompt")
    if post_prompt is None:
        return _deferred_section(
            "post_prompt was not found in the supplied server source.",
            request_fields=[],
            success_response_fields=[],
            error_response_fields=[],
        )

    observed_fields = _extract_string_keys_from_json_data(post_prompt)
    # Preserve ComfyUI's handler-order contract for predictable artifact diffs.
    request_order = [
        "number",
        "front",
        "prompt",
        "prompt_id",
        "partial_execution_targets",
        "extra_data",
        "client_id",
    ]
    traceability = _traceability(server_source, "post_prompt", "ast-structural")
    request_fields = [
        _field(
            name,
            "json",
            name == "prompt",
            "unknown",
            PROMPT_REQUEST_FIELD_DESCRIPTIONS[name],
            traceability,
        )
        for name in request_order
        if name in observed_fields
    ]
    success_names, error_names = _json_response_payload_fields(post_prompt)
    success_response_fields = [
        _field(
            name,
            "response_json",
            True,
            "unknown",
            f"Response field `{name}` observed in the successful POST /prompt JSON payload.",
            traceability,
        )
        for name in sorted(success_names)
    ]
    error_response_fields = [
        _field(
            name,
            "response_json",
            True,
            "unknown",
            f"Response field `{name}` observed in an error POST /prompt JSON payload.",
            traceability,
        )
        for name in sorted(error_names)
    ]
    return {
        "request_fields": request_fields,
        "success_response_fields": success_response_fields,
        "error_response_fields": error_response_fields,
    }


def _nearest_function_name(node: ast.AST) -> str:
    parent = getattr(node, "_parent", None)
    while parent is not None:
        if isinstance(parent, ast.FunctionDef | ast.AsyncFunctionDef):
            return parent.name
        parent = getattr(parent, "_parent", None)
    return "module"


def _error_entry_from_dict(node: ast.Dict, source_file: str) -> dict | None:
    keys = node.keys
    values = node.values
    type_value = None
    message_value = None
    extra_info_fields: list[str] = []
    for key, value in zip(keys, values, strict=False):
        if not isinstance(key, ast.Constant) or not isinstance(key.value, str):
            continue
        if key.value == "type" and isinstance(value, ast.Constant) and isinstance(value.value, str):
            type_value = value.value
        elif (
            key.value == "message"
            and isinstance(value, ast.Constant)
            and isinstance(value.value, str)
        ):
            message_value = value.value
        elif key.value == "extra_info" and isinstance(value, ast.Dict):
            extra_info_fields = _literal_dict_keys(value)
    if type_value is None:
        return None
    source_function = _nearest_function_name(node)
    entry = {
        "type": type_value,
        "summary": PROMPT_ERROR_SUMMARIES.get(type_value, message_value or type_value),
        "source_function": source_function,
        "traceability": _traceability(source_file, source_function, "ast-structural"),
        "extraction_method": "ast-structural",
    }
    if extra_info_fields:
        entry["extra_info_fields"] = extra_info_fields
    return entry


def _is_prompt_validation_context(function_name: str) -> bool:
    return function_name == "post_prompt" or "validate" in function_name.lower()


def _extract_prompt_validation_errors(
    execution_text: str,
    server_text: str,
    *,
    execution_source: str | None = None,
    server_source: str | None = None,
) -> dict:
    entries: dict[str, dict] = {}
    unknown_types: set[str] = set()
    for source_text, source_file in (
        (server_text, server_source),
        (execution_text, execution_source),
    ):
        tree = _parse_python(source_text)
        if tree is None:
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Dict):
                entry = _error_entry_from_dict(node, source_file or "unknown")
                if entry is not None:
                    if not _is_prompt_validation_context(entry["source_function"]):
                        continue
                    if entry["type"] not in PROMPT_ERROR_SUMMARIES:
                        unknown_types.add(entry["type"])
                    entries.setdefault(entry["type"], entry)

    scoped_note = (
        "Prompt validation error extraction is scoped to validation functions; "
        "unrelated literal dictionaries with type keys are ignored."
    )
    if not entries:
        section = _deferred_section(
            "No prompt validation error dictionaries were found in scoped validation contexts.",
            error_types=[],
        )
        section["deferred"] = [scoped_note]
        return section
    deferred = [
        "Runtime node-specific validation messages from custom nodes are not statically knowable.",
        scoped_note,
    ]
    if unknown_types:
        deferred.append(
            "unknown prompt validation error types were preserved without curated summaries: "
            + ", ".join(sorted(unknown_types))
            + "."
        )
    return {
        "error_types": [entries[key] for key in sorted(entries)],
        "coverage": "source-backed",
        "deferred": deferred,
    }


def _extract_queue_history_contract(
    server_text: str,
    execution_text: str,
    *,
    server_source: str | None = None,
    execution_source: str | None = None,
) -> dict:
    server_functions = _function_nodes(_parse_python(server_text))
    execution_functions = _function_nodes(_parse_python(execution_text))
    sections = []

    if "get_queue" in server_functions:
        traceability = _traceability(server_source, "get_queue", "ast-structural")
        sections.extend(
            [
                {
                    "name": "queue_running",
                    "summary": "GET /queue returns the current running queue items after sensitive fields are removed.",
                    "traceability": traceability,
                    "coverage": "deferred",
                    "deferred_reason": "Exact queue item tuple contents depend on runtime prompt payloads.",
                },
                {
                    "name": "queue_pending",
                    "summary": "GET /queue returns pending queue items after sensitive fields are removed.",
                    "traceability": traceability,
                    "coverage": "deferred",
                    "deferred_reason": "Exact queue item tuple contents depend on runtime prompt payloads.",
                },
            ]
        )

    if {"get_history", "get_history_prompt_id", "post_history"}.issubset(server_functions):
        sections.append(
            {
                "name": "history",
                "summary": "GET /history lists stored prompt history, GET /history/{prompt_id} filters by id, and POST /history clears or deletes entries.",
                "traceability": _traceability(server_source, "get_history", "ast-structural"),
                "coverage": "deferred",
                "deferred_reason": "Stored history includes execution-produced outputs and metadata that vary by node/runtime.",
            }
        )

    if "task_done" in execution_functions:
        sections.append(
            {
                "name": "task_done",
                "summary": "PromptQueue.task_done stores prompt, outputs, status, and execution history_result data by prompt id.",
                "traceability": _traceability(execution_source, "task_done", "ast-structural"),
                "coverage": "deferred",
                "deferred_reason": "history_result is produced by execution outputs and may contain runtime-specific payloads.",
            }
        )

    if "PromptQueue" in {
        node.name
        for node in ast.walk(_parse_python(execution_text) or ast.Module(body=[], type_ignores=[]))
        if isinstance(node, ast.ClassDef)
    }:
        sections.append(
            {
                "name": "status",
                "summary": "PromptQueue.ExecutionStatus defines status_str, completed, and messages for stored history status.",
                "traceability": _traceability(
                    execution_source, "ExecutionStatus", "ast-structural"
                ),
                "coverage": "source-backed",
            }
        )

    if "system_stats" in server_functions or "post_free" in server_functions:
        sections.append(
            {
                "name": "flags",
                "summary": "Status-related metadata includes system_stats top-level keys such as system and devices; queue flags can request model unload or memory free actions.",
                "traceability": _traceability(server_source, "system_stats", "ast-structural"),
                "coverage": "source-backed",
            }
        )

    if not sections:
        return _deferred_section(
            "Queue, history, and status source functions were not found in supplied sources.",
            sections=[],
        )
    return {"sections": sections}


def extract_server_runtime_contracts(
    server_text: str,
    execution_text: str,
    *,
    server_source: str | None = None,
    execution_source: str | None = None,
) -> dict:
    return {
        "prompt_submission_contract": _extract_prompt_submission_contract(
            server_text,
            server_source=server_source,
        ),
        "prompt_validation_errors": _extract_prompt_validation_errors(
            execution_text,
            server_text,
            execution_source=execution_source,
            server_source=server_source,
        ),
        "queue_history_contract": _extract_queue_history_contract(
            server_text,
            execution_text,
            server_source=server_source,
            execution_source=execution_source,
        ),
    }


def extract_endpoints(source_text: str) -> list[dict]:
    lines = source_text.splitlines()
    endpoints: list[dict] = []
    matches = _find_decorator_matches(lines)

    for k, (index, match) in enumerate(matches):
        decorator_kind, route = match.groups()
        method = decorator_kind.upper() if decorator_kind != "route" else "ROUTE"

        if k + 1 < len(matches):
            next_index = matches[k + 1][0]
        else:
            next_index = len(lines)

        block = _get_function_block(lines, index, next_index)
        doc_match = DOCSTRING_RE.search(block)
        description = ""
        if doc_match:
            description = " ".join(doc_match.group(2).strip().split())

        returns = infer_returns(block, source_text)
        parameters = extract_parameters(route, block, source_text)

        notes = []
        if method in ("POST", "PUT", "PATCH") and parameters:
            notes.append(
                "Parameters marked 'required' reflect static subscript access "
                "patterns, not API-level requiredness. Only fields that cause "
                "the handler to return an error status when missing are truly "
                "mandatory. Consult the prose API docs for precise "
                "mutation-request contracts."
            )

        endpoints.append(
            {
                "route": route,
                "method": method,
                "description": description,
                "parameters": parameters,
                "returns": returns,
                "notes": notes,
            }
        )

    return endpoints


def main() -> int:
    parser = argparse.ArgumentParser(description="Extract ComfyUI server routes to JSON")
    parser.add_argument("server_path", nargs="?", help="Path to ComfyUI server.py")
    parser.add_argument(
        "--execution-path",
        default=None,
        help="Optional path to ComfyUI execution.py; defaults to a sibling of server.py when present",
    )
    parser.add_argument("--version", default=None, help="Pinned upstream version or tag")
    parser.add_argument("--commit", default=None, help="Pinned upstream commit hash")
    parser.add_argument("--output", default=str(OUTPUT_PATH), help="Output JSON path")
    args = parser.parse_args()

    if not args.server_path:
        parser.print_usage()
        return 1

    source_path = Path(args.server_path)
    source_text = source_path.read_text(encoding="utf-8")
    endpoints = extract_endpoints(source_text)
    execution_path = (
        Path(args.execution_path) if args.execution_path else source_path.with_name("execution.py")
    )
    execution_text = ""
    metadata_sources = [normalize_repo_relative_path(source_path, REPO_ROOT)]
    execution_source = ""
    if execution_path.exists():
        execution_text = execution_path.read_text(encoding="utf-8")
        execution_source = normalize_repo_relative_path(execution_path, REPO_ROOT)
        metadata_sources.append(execution_source)

    runtime_contracts = extract_server_runtime_contracts(
        source_text,
        execution_text,
        server_source=metadata_sources[0],
        execution_source=execution_source,
    )

    payload = {
        "metadata": {
            "sources": metadata_sources,
            "extracted_date": datetime.now().strftime("%Y-%m-%d"),
            "version": args.version or "unversioned",
            "commit": args.commit,
        },
        "coverage": ENDPOINT_COVERAGE,
        "endpoints": endpoints,
        **runtime_contracts,
    }

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"Extracted {len(endpoints)} endpoints to {display_path(output_path)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
